import { Bot } from "lucide-react";
import { Panel } from "@/components/ui";
import type { AiReport } from "@/types/api";
import type { TranslationKey } from "@/i18n";

export function AiReportPanel({ report, t }: { report: AiReport | null; t: (key: TranslationKey) => string }) {
  return (
    <Panel className="p-5">
      <div className="flex items-center justify-between">
        <h2 className="text-base font-semibold text-text">{t("aiMonthlyReport")}</h2>
        <Bot size={18} className="text-cyan" />
      </div>
      <p className="mt-4 text-sm leading-6 text-muted">
        {report?.summary ??
          "Expenses are healthy overall, but Shopping exceeded its monthly budget. Food is close to its limit and should be watched during the next week."}
      </p>
      <div className="mt-4 rounded-md border border-cyan/20 bg-cyan/8 p-3 text-sm leading-5 text-cyan">
        {report ? "Generated by backend stub provider" : t("syncReady")}
      </div>
    </Panel>
  );
}
